<?php
  const QUESTION_TOPIC_BST = "BST";
  const QUESTION_TOPIC_HEAP = "Heap";

  const QUESTION_TYPE_SEARCH = "Search";
  const QUESTION_TYPE_TRAVERSAL = "Traversal";

  const QUESTION_SUB_TYPE_NONE = "";
  const QUESTION_SUB_TYPE_INORDER_TRAVERSAL = "Inorder";
  const QUESTION_SUB_TYPE_PREORDER_TRAVERSAL = "Preorder";
  const QUESTION_SUB_TYPE_POSTORDER_TRAVERSAL = "Postorder";

  const ANSWER_TYPE_VERTEX = "vertex";

  const ANSWER_AMT_ONE = 1;
  const ANSWER_AMT_MULTIPLE = 2;

  const MODE_GENERATE_QUESTIONS = 1;
  const MODE_CHECK_ANSWERS = 2;
?>